--新建表格，其他的手动在PL/SQL界面修改
--DROP TABLE SAJET.G_RETURNSPLIT_LOG;
CREATE TABLE SAJET.G_RETURNSPLIT_LOG (
	"DISPLAY_SN" VARCHAR2(50 BYTE),
	"FRAME_SN" VARCHAR2(50 BYTE),
	"TERMINAL_ID" NUMBER,
	"PROCESS_ID" NUMBER,
	"UPDATE_USERID" VARCHAR2(50 BYTE),
	"UPDATE_TIME" DATE DEFAULT SYSDATE 
)
COMMENT ON COLUMN SAJET.G_RETURNSPLIT_LOG."DISPLAY_SN" IS '屏显SN';
COMMENT ON COLUMN SAJET.G_RETURNSPLIT_LOG."FRAME_SN" IS '框架SN';
COMMENT ON COLUMN SAJET.G_RETURNSPLIT_LOG."TERMINAL_ID" IS '站点ID';
COMMENT ON COLUMN SAJET.G_RETURNSPLIT_LOG."PROCESS_ID" IS '制程ID';
COMMENT ON COLUMN SAJET.G_RETURNSPLIT_LOG."UPDATE_USERID" IS '登录人';
COMMENT ON COLUMN SAJET.G_RETURNSPLIT_LOG."UPDATE_TIME" IS '记录时间';

